### ISSUE TITLE
New DokuWiki Update messes with the Size

### ISSUE THREAD

**Issue by Vitamin-X** [jakob1111/dokuwiki-plugin-flowcharts#27]
just updated to Release rc2022-06-26 "Igor" RC2

and the CSS file in /lib/exe/css.php contains "svg{width:auto;height:1.2em;}" and thats messing with the hight

**Comment by nhenryberends** [comment]
I would love to see even a hackey workaround—as is, all my flowcharts are very small, and I can't possibly zoom in far enough to get them legible.

**Comment by arlt** [comment]
`mermaid-override.css`:
```css
.mermaid svg {
	width: 100%;
	height: auto;
}
```
The `height` line fixed it here.

**Comment by axelhahn** [comment]
The mermaid-override.css was the right place on my installation too.
But the width of 100% shows some quite large svg graphs. I commented the wudth and need the `height: auto` only:
```css
.mermaid svg {
	/*
	width: 100%;
	*/
	height: auto;
}
```

**Comment by arlt** [comment]
@axelhahn maybe `width: unset;` is an option, too. But i havent tested this.

**Comment by axelhahn** [comment]
@arlt FYI both variants of _mermaid-override.css_ show the same behaviour (both are OK):

```css
.mermaid svg {
	/*
	width: 100%;
	*/
	height: auto;
}
```
and
```css
.mermaid svg {
	width: unset;
	height: auto;
}
```
